### ISSUE TITLE
运行后提示："创建本地目录错误：mkdir：系统找不到指定的路径。"

### ISSUE THREAD

**Issue by truelove2017ye** [imshuai/AlistAutoStrm#1]
我在config.json中设置
            "remote-dir": "/",
            "local-dir": "D:/emby/AlistAutoStrm/bin",
运行后出错如下：
D:\emby\AlistAutoStrm\bin>ass-v1.1.1-windows-amd64.exe --config config.json
time="2024-09-18 18:40:16" level=info msg="read config file success"
time="2024-09-18 18:40:16" level=info msg="login success, username: truelove"
time="2024-09-18 18:40:16" level=info msg="start generate .strm file to "
time="2024-09-18 18:40:16" level=error msg="create local directory error: mkdir : The system cannot find the path specified."

求指教，谢谢！

**Comment by imshuai** [comment]
在Windows系统中执行，需要修改配置文件中的路径写法，因为windows系统中路径的分隔符是反斜杠，而反斜杠因为是特殊符号，需要加反斜杠转义。
例如：`D:\emby\AlistAutoStrm\bin`就应该写成`D:\\emby\\AlistAutoStrm\\bin`  
故此，更建议使用相对路径的写法，然后将可执行文件和配置文件放到对应的目录中再执行，例如：  
```json
"remote-dir": "/",
"local-dir": "data/strm/movie",
```
